Add index to call trace DB to speed up lookup by module
Instagram/MonkeyType pull request #301
Opened 2023-08-26 13:22 UTC by Feuermurmel

See https://github.com/Instagram/MonkeyType/issues/300.

2023-09-15 00:20 UTC, carljm commented on monkeytype/db/sqlite.py
> +            )
```suggestion
            conn.execute(query.format(table=table))
```

2023-09-15 00:20 UTC, carljm commented on monkeytype/db/sqlite.py
> +        """
```suggestion
        """,
```

2023-09-15 00:22 UTC, carljm commented
Hi @Feuermurmel, this looks great! It needs a couple minor tweaks (per my comments) to pass our autoformatter; unfortunately it looks like you didn't check the box that would allow me to make those updates to your PR myself, so are you willing to accept my suggestions so we can get this merged? Thank you!

2023-09-15 00:23 UTC, carljm requested changes
Putting it back in your queue for the formatting updates.

2023-09-19 11:02 UTC, Feuermurmel commented
> Hi @Feuermurmel, this looks great! It needs a couple minor tweaks (per my comments) to pass our autoformatter

Same issue here: https://github.com/Instagram/MonkeyType/pull/302#issuecomment-1725279372

What's the expectation here? Should I only format the files that I touched and leave the rest as-is, and that will pass the checks?

2023-09-20 16:48 UTC, carljm commented
Just format the files within `monkeytype/` directory, and that should also format only the files you touched. Or in this case, you can just accept my suggested edits above and that will also pass the formatter check.

2023-09-21 16:32 UTC, Feuermurmel commented
It should be fixed now!

2023-09-21 19:17 UTC, merged